//! Daemon launcher: spawns the `serctl_daemon` binary from the same install
//! directory and hands it a per-boot activation secret through an inherited
//! stdin pipe. Secrets never enter argv, the environment, or a log.
//!
//! Phase 2: the global broker boot identity (instance id + activation secret)
//! is generated by the first CLI under the startup singleton and published
//! through the protected runtime descriptor for every later CLI.

use anyhow::{bail, Context, Result};
use zeroize::Zeroizing;

/// Bound for daemon setup, mirrored from `serctl_daemon::daemon::CONTROL_SETUP_TIMEOUT`.
pub const DAEMON_STARTUP_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(30);

#[cfg(windows)]
const DAEMON_EXE_NAME: &str = "serctl_daemon.exe";
#[cfg(not(windows))]
const DAEMON_EXE_NAME: &str = "serctl_daemon";

/// Resolve the daemon executable: the known filename in the directory that
/// contains the running `serctl_cli` binary. Never search PATH.
pub fn daemon_exe_path() -> Result<std::path::PathBuf> {
    let mut path = std::env::current_exe().context("resolve serctl_cli executable path")?;
    if !path.pop() {
        bail!("serctl_cli executable path has no parent directory");
    }
    let exe = path.join(DAEMON_EXE_NAME);
    if !exe.is_file() {
        bail!(
            "{} not found beside the serctl_cli binary; reinstall both binaries together",
            exe.display()
        );
    }
    Ok(exe)
}

/// Frame the global-mode activation secret for the daemon's inherited stdin
/// channel: magic, 32-bit little-endian length, base64 payload.
fn secret_bootstrap_frame(secret: &serctl_protocol::v6::ActivationSecret) -> Zeroizing<Vec<u8>> {
    let encoded = secret.to_base64();
    let mut frame = Zeroizing::new(Vec::with_capacity(8 + encoded.len()));
    frame.extend_from_slice(SECRET_FRAME_MAGIC);
    frame.extend_from_slice(&(encoded.len() as u32).to_le_bytes());
    frame.extend_from_slice(encoded.as_bytes());
    frame
}

const SECRET_FRAME_MAGIC: &[u8; 4] = b"SD02";

/// Launch the per-user/per-vault global broker. The caller must hold the
/// startup singleton (see `serctl_core::daemon_runtime::acquire_startup_lock`).
/// Returns the generated boot identity; the daemon publishes its runtime
/// descriptor and activation secret so later CLIs can authenticate with it.
pub fn spawn_global_daemon() -> Result<(
    serctl_protocol::v6::InstanceId,
    serctl_protocol::v6::ActivationSecret,
)> {
    let (instance, secret, _child) = spawn_global_daemon_with_stdio(false)?;
    Ok((instance, secret))
}

/// `serctl_cli up`: run the global broker in the foreground until it exits,
/// without letting this console's Ctrl-C kill the supervisor before the daemon
/// has performed its own coordinated shutdown. Returns the daemon's exit code.
pub async fn run_global_daemon_foreground() -> Result<i32> {
    let (_instance, _secret, mut child) = spawn_global_daemon_with_stdio(true)?;
    supervise_daemon_foreground(&mut child).await
}

/// Spawn the global broker with either inherited or detached stdio.
fn spawn_global_daemon_with_stdio(
    foreground: bool,
) -> Result<(
    serctl_protocol::v6::InstanceId,
    serctl_protocol::v6::ActivationSecret,
    std::process::Child,
)> {
    use std::io::Write as _;

    let exe = daemon_exe_path()?;
    let instance = serctl_protocol::v6::InstanceId::random();
    let secret = serctl_protocol::v6::ActivationSecret::random();
    let mut command = std::process::Command::new(&exe);
    command
        .arg("--global-instance")
        .arg(instance.as_hex())
        .stdin(std::process::Stdio::piped());
    if foreground {
        command
            .stdout(std::process::Stdio::inherit())
            .stderr(std::process::Stdio::inherit());
    } else {
        // The broker is a background service: it logs nowhere in production
        // and outlives every CLI that launches it.
        command
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null());
    }
    let mut child = command.spawn().with_context(|| {
        format!(
            "start {} --global-instance {}",
            exe.display(),
            instance.as_hex()
        )
    })?;
    let mut stdin = child
        .stdin
        .take()
        .context("daemon spawn produced no stdin pipe")?;
    let frame = secret_bootstrap_frame(&secret);
    stdin
        .write_all(&frame)
        .context("write daemon activation secret frame")?;
    stdin
        .flush()
        .context("flush daemon activation secret frame")?;
    // Dropping the write end signals end-of-frame to the daemon's bounded
    // reader; the daemon fails closed if anything else ever reaches stdin.
    drop(stdin);
    Ok((instance, secret, child))
}

/// Supervise a foreground daemon child: swallow Ctrl-C here because the
/// daemon is a sibling process attached to the same console and receives the
/// event itself; when it exits we mirror its status.
async fn supervise_daemon_foreground(child: &mut std::process::Child) -> Result<i32> {
    let mut interrupt = Box::pin(tokio::signal::ctrl_c());
    let mut poll = tokio::time::interval(std::time::Duration::from_millis(100));
    poll.set_missed_tick_behavior(tokio::time::MissedTickBehavior::Delay);
    let status = loop {
        tokio::select! {
            _ = &mut interrupt => {
                // Keep the supervisor alive; Ctrl-C is the daemon's signal.
                interrupt = Box::pin(tokio::signal::ctrl_c());
            }
            _ = poll.tick() => {
                match child.try_wait() {
                    Ok(Some(status)) => break status,
                    Ok(None) => {}
                    Err(error) => return Err(error).context("wait for serctl_daemon exit"),
                }
            }
        }
    };
    Ok(status.code().unwrap_or(1))
}
