[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-SelfTestCondition {
    param(
        [Parameter(Mandatory = $true)][bool]$Condition,
        [Parameter(Mandatory = $true)][string]$Message
    )
    if (-not $Condition) {
        throw "release consistency self-test failed: $Message"
    }
}

function Write-Utf8NoBom {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Content
    )
    [System.IO.File]::WriteAllText(
        $Path,
        $Content,
        [System.Text.UTF8Encoding]::new($false)
    )
}

function Invoke-FixtureGit {
    param([Parameter(Mandatory = $true)][string[]]$GitArguments)
    $previousErrorActionPreference = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    try {
        & git -c core.autocrlf=false -C $script:FixtureRoot @GitArguments *> $null
        $gitExitCode = $LASTEXITCODE
    }
    finally {
        $ErrorActionPreference = $previousErrorActionPreference
    }
    Assert-SelfTestCondition ($gitExitCode -eq 0) (
        "git command failed: git $($GitArguments -join ' ')"
    )
}

function Invoke-ExpectedVerifierFailure {
    param(
        [Parameter(Mandatory = $true)][string]$Description,
        [Parameter(Mandatory = $true)][string]$ExpectedMessage,
        [Parameter(Mandatory = $true)][scriptblock]$Action
    )
    $caught = $null
    try {
        & $Action *> $null
    }
    catch {
        $caught = $_
    }
    Assert-SelfTestCondition ($null -ne $caught) (
        "$Description unexpectedly passed"
    )
    Assert-SelfTestCondition (
        $caught.Exception.Message.Contains($ExpectedMessage)
    ) (
        "$Description failed for the wrong reason: $($caught.Exception.Message)"
    )
}

$repositoryRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$fixtureBase = Join-Path $repositoryRoot 'target/release-consistency-selftests'
[void][System.IO.Directory]::CreateDirectory($fixtureBase)
$script:FixtureRoot = Join-Path $fixtureBase (
    "serctl-release-consistency-selftest-" + [guid]::NewGuid().ToString('N')
)
$fixtureFullPath = [System.IO.Path]::GetFullPath($script:FixtureRoot)
$fixtureBasePrefix = [System.IO.Path]::GetFullPath($fixtureBase).TrimEnd(
    [System.IO.Path]::DirectorySeparatorChar
) + [System.IO.Path]::DirectorySeparatorChar
Assert-SelfTestCondition (
    $fixtureFullPath.StartsWith(
        $fixtureBasePrefix,
        [System.StringComparison]::OrdinalIgnoreCase
    ) -and
    [System.IO.Path]::GetFileName($fixtureFullPath).StartsWith(
        'serctl-release-consistency-selftest-',
        [System.StringComparison]::Ordinal
    )
) 'temporary fixture path escaped the dedicated self-test prefix'

$version = '0.3.0-beta.2'
$tag = "v$version"
$verifier = Join-Path $script:FixtureRoot 'scripts/Verify-ReleaseConsistency.ps1'
$readmePath = Join-Path $script:FixtureRoot 'README.md'
$changelogPath = Join-Path $script:FixtureRoot 'CHANGELOG.md'
$crateSourcePath = Join-Path $script:FixtureRoot 'crates/fixture/src/lib.rs'
$fuzzLockPath = Join-Path $script:FixtureRoot 'fuzz/Cargo.lock'

try {
    foreach ($directory in @(
        'scripts',
        'docs',
        'fuzz',
        'crates/fixture/src'
    )) {
        [void][System.IO.Directory]::CreateDirectory(
            (Join-Path $script:FixtureRoot $directory)
        )
    }
    [System.IO.File]::Copy(
        (Join-Path $PSScriptRoot 'Verify-ReleaseConsistency.ps1'),
        $verifier
    )
    Write-Utf8NoBom (Join-Path $script:FixtureRoot 'Cargo.toml') @"
[workspace]
members = ["crates/fixture"]
resolver = "2"

[workspace.package]
version = "$version"
edition = "2021"
"@
    Write-Utf8NoBom (Join-Path $script:FixtureRoot 'crates/fixture/Cargo.toml') @"
[package]
name = "release-consistency-fixture"
version.workspace = true
edition.workspace = true
"@
    Write-Utf8NoBom $crateSourcePath "pub fn fixture() -> bool { true }`n"
    Write-Utf8NoBom (Join-Path $script:FixtureRoot 'Cargo.lock') @"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "release-consistency-fixture"
version = "$version"
"@
    Write-Utf8NoBom (Join-Path $script:FixtureRoot 'fuzz/Cargo.toml') @"
[package]
name = "release-consistency-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
release-consistency-fixture = { path = "../crates/fixture" }

[workspace]
members = ["."]
"@
    $fuzzLock = @"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "release-consistency-fixture"
version = "$version"

[[package]]
name = "release-consistency-fuzz"
version = "0.0.0"
dependencies = [
 "release-consistency-fixture",
]
"@
    Write-Utf8NoBom $fuzzLockPath $fuzzLock
    $datedChangelog = "## $tag - 2026-01-01`n`n- Fixture release.`n"
    Write-Utf8NoBom $changelogPath $datedChangelog
    $readme = "<!-- release-marker: $tag -->`nFixture.`n"
    Write-Utf8NoBom $readmePath $readme
    Write-Utf8NoBom (
        Join-Path $script:FixtureRoot 'docs/serctl-user-guide.md'
    ) "<!-- applicable-version: $tag -->`nFixture.`n"
    Write-Utf8NoBom (
        Join-Path $script:FixtureRoot 'docs/serctl-architecture-security.html'
    ) "<html data-release-predecessor=`"$tag`"></html>`n"

    Invoke-FixtureGit @('init', '--quiet')
    Invoke-FixtureGit @('config', 'user.name', 'serctl-self-test')
    Invoke-FixtureGit @('config', 'user.email', 'serctl-self-test.invalid')
    Invoke-FixtureGit @('add', '--all')
    Invoke-FixtureGit @('commit', '--quiet', '-m', 'fixture release')
    Invoke-FixtureGit @('tag', '-a', $tag, '-m', 'fixture annotated release')

    & $verifier -Tag $tag -RequireGitTag *> $null

    Invoke-FixtureGit @('tag', '-d', $tag)
    Invoke-FixtureGit @('tag', $tag)
    Invoke-ExpectedVerifierFailure `
        -Description 'lightweight release tag' `
        -ExpectedMessage 'release tag must be an annotated tag object' `
        -Action { & $verifier -Tag $tag -RequireGitTag }

    Invoke-FixtureGit @('tag', '-d', $tag)
    Invoke-FixtureGit @('tag', '-a', 'nested-target', '-m', 'nested target')
    Invoke-FixtureGit @('tag', '-a', $tag, 'nested-target', '-m', 'nested release')
    Invoke-ExpectedVerifierFailure `
        -Description 'annotated tag pointing to another tag' `
        -ExpectedMessage 'must point directly to a commit' `
        -Action { & $verifier -Tag $tag -RequireGitTag }

    Invoke-FixtureGit @('tag', '-d', $tag)
    Invoke-FixtureGit @('tag', '-d', 'nested-target')
    Invoke-FixtureGit @('tag', '-a', $tag, '-m', 'fixture annotated release')
    Write-Utf8NoBom $crateSourcePath "pub fn fixture() -> bool { false }`n"
    Invoke-FixtureGit @('add', '--all')
    Invoke-FixtureGit @('commit', '--quiet', '-m', 'later fixture commit')
    Invoke-ExpectedVerifierFailure `
        -Description 'annotated tag at the wrong commit' `
        -ExpectedMessage 'does not equal checked-out HEAD' `
        -Action { & $verifier -Tag $tag -RequireGitTag }

    Invoke-FixtureGit @('tag', '-d', $tag)
    Invoke-FixtureGit @('tag', '-a', $tag, '-m', 'fixture current release')
    Write-Utf8NoBom $crateSourcePath "pub fn fixture() -> bool { true }`n"
    Invoke-ExpectedVerifierFailure `
        -Description 'dirty annotated-tag checkout' `
        -ExpectedMessage 'tag checkout is not clean' `
        -Action { & $verifier -Tag $tag -RequireGitTag }
    Write-Utf8NoBom $crateSourcePath "pub fn fixture() -> bool { false }`n"

    Write-Utf8NoBom $readmePath (
        $readme + "<!-- release-marker: v1.0.0-beta -->`n"
    )
    Invoke-ExpectedVerifierFailure `
        -Description 'duplicate stale release document marker' `
        -ExpectedMessage 'must contain exactly one release identity marker' `
        -Action { & $verifier -Tag $tag }
    Write-Utf8NoBom $readmePath $readme

    Write-Utf8NoBom $changelogPath (
        "## v1.0.0-beta - Unreleased`n`n- Candidate work.`n`n" +
        $datedChangelog
    )
    & $verifier `
        -Tag $tag `
        -AllowLeadingUnreleased `
        -ExpectedUnreleasedTag 'v1.0.0-beta' *> $null
    Invoke-ExpectedVerifierFailure `
        -Description 'development check with the wrong expected candidate' `
        -ExpectedMessage 'leading Unreleased entry does not equal expected candidate' `
        -Action {
            & $verifier `
                -Tag $tag `
                -AllowLeadingUnreleased `
                -ExpectedUnreleasedTag 'v1.0.0-rc'
        }
    Invoke-ExpectedVerifierFailure `
        -Description 'development check without an expected candidate' `
        -ExpectedMessage 'AllowLeadingUnreleased requires ExpectedUnreleasedTag' `
        -Action { & $verifier -Tag $tag -AllowLeadingUnreleased }

    Write-Utf8NoBom $fuzzLockPath ($fuzzLock.Replace(
        "version = `"$version`"",
        'version = "9.9.9"'
    ))
    Invoke-ExpectedVerifierFailure `
        -Description 'stale internal package version in fuzz/Cargo.lock' `
        -ExpectedMessage "fuzz/Cargo.lock package 'release-consistency-fixture' has version '9.9.9'" `
        -Action { & $verifier -Tag $tag -AllowLeadingUnreleased -ExpectedUnreleasedTag 'v1.0.0-beta' }
    Write-Utf8NoBom $fuzzLockPath $fuzzLock

    [System.IO.File]::AppendAllText(
        (Join-Path $script:FixtureRoot 'Cargo.lock'),
        "`n[[package]]`nname = `"release-consistency-fixture`"`nversion = `"9.9.9`"`n",
        [System.Text.UTF8Encoding]::new($false)
    )
    Invoke-ExpectedVerifierFailure `
        -Description 'duplicate workspace package name in Cargo.lock' `
        -ExpectedMessage "Cargo.lock must contain exactly one package named 'release-consistency-fixture'" `
        -Action { & $verifier -Tag $tag }

}
finally {
    if ([System.IO.Directory]::Exists($fixtureFullPath)) {
        Assert-SelfTestCondition (
            $fixtureFullPath.StartsWith(
                $fixtureBasePrefix,
                [System.StringComparison]::OrdinalIgnoreCase
            )
        ) 'refusing to clean a release-consistency fixture outside its target directory'
        foreach ($file in [System.IO.Directory]::EnumerateFiles(
            $fixtureFullPath,
            '*',
            [System.IO.SearchOption]::AllDirectories
        )) {
            [System.IO.File]::SetAttributes($file, [System.IO.FileAttributes]::Normal)
        }
        foreach ($directory in [System.IO.Directory]::EnumerateDirectories(
            $fixtureFullPath,
            '*',
            [System.IO.SearchOption]::AllDirectories
        )) {
            [System.IO.File]::SetAttributes($directory, [System.IO.FileAttributes]::Directory)
        }
        [System.IO.File]::SetAttributes(
            $fixtureFullPath,
            [System.IO.FileAttributes]::Directory
        )
        [System.IO.Directory]::Delete($fixtureFullPath, $true)
    }
}

Write-Host 'Release consistency synthetic Git self-test passed.'
